# edots Hyprland
# Archivo principal: deja lo estable aquí y personaliza en conf/custom.conf.

source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/looknfeel.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/custom.conf
