general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.local/share/edots/wallpapers/harbor.png
    blur_passes = 3
    blur_size = 8
    noise = 0.02
}

input-field {
    monitor =
    size = 320, 58
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    outer_color = rgba(95d0b5ee)
    inner_color = rgba(171b20dd)
    font_color = rgba(e8edf2ff)
    fade_on_empty = false
    placeholder_text = Contraseña
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(e8edf2ff)
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    position = 0, 90
    halign = center
    valign = center
}
