font_family JetBrainsMono Nerd Font
font_size 11.5
disable_ligatures never

background #0f1417
foreground #e8edf2
selection_background #2c363e
selection_foreground #e8edf2
cursor #5fd0b5
url_color #9db4ff

active_tab_background #5fd0b5
active_tab_foreground #0f1417
inactive_tab_background #222b32
inactive_tab_foreground #94a2ad

color0 #0f1417
color1 #f26d6d
color2 #5fd0b5
color3 #f4a261
color4 #9db4ff
color5 #d690ff
color6 #63cdda
color7 #e8edf2
color8 #59656f
color9 #ff8a8a
color10 #7fe4cc
color11 #ffd08a
color12 #b4c4ff
color13 #e0adff
color14 #92e6ef
color15 #ffffff

confirm_os_window_close 0
enable_audio_bell no
window_padding_width 8
tab_bar_edge bottom
tab_bar_style powerline
