$mainMod = SUPER
$terminal = kitty
$launcher = fuzzel
$browser = xdg-open https://duckduckgo.com
$files = nautilus --new-window

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, SPACE, exec, $launcher
bind = $mainMod SHIFT, B, exec, $browser
bind = $mainMod, E, exec, $files
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, Q, exec, qs ipc call shell togglePower
bind = $mainMod, C, exec, qs ipc call shell toggleDashboard
bind = $mainMod, F, fullscreen
bind = $mainMod, T, togglefloating
bind = $mainMod, P, pseudo
bind = $mainMod SHIFT, T, layoutmsg, togglesplit
bind = $mainMod SHIFT, R, exec, hyprctl reload && qs ipc call shell reload

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

bind = $mainMod CTRL, H, resizeactive, -40 0
bind = $mainMod CTRL, RIGHT, resizeactive, 40 0
bind = $mainMod CTRL, K, resizeactive, 0 -40
bind = $mainMod CTRL, J, resizeactive, 0 40

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, S, togglespecialworkspace, scratch
bind = $mainMod SHIFT, S, movetoworkspace, special:scratch

bind = , PRINT, exec, edots-screenshot area
bind = $mainMod, PRINT, exec, edots-screenshot full
bind = $mainMod, V, exec, edots-clipboard
bind = $mainMod, ESCAPE, exec, qs ipc call shell togglePower
bind = $mainMod CTRL, L, exec, pidof hyprlock || hyprlock

bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindel = , XF86AudioLowerVolume, exec, pamixer -d 5
bindl = , XF86AudioMute, exec, pamixer -t
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
