windowrule = float on, match:class ^(pavucontrol)$
windowrule = size 900 620, match:class ^(pavucontrol)$
windowrule = center on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = size 900 620, match:class ^(blueman-manager)$
windowrule = center on, match:class ^(blueman-manager)$
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(org.gnome.Calculator)$
windowrule = center on, match:class ^(org.gnome.Calculator)$
layerrule = blur on, match:namespace quickshell
layerrule = blur on, match:namespace launcher
